#!/usr/bin/env bash
# Install and configure nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
	index index.html;
    }
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

sudo bash -c 'cat <<EOF > /usr/share/nginx/html/index.html
Hello World!
EOF'

sudo service nginx start
