#!/usr/bin/env bash
# Install and configure nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
	index index.html;

	rewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	add_header X-Served-By $HOSTNAME;
    }
    error_page 404 /error-404.html;
}
EOF'

sudo bash -c 'cat <<EOF > /usr/share/nginx/html/index.html
Hello World!
EOF'

sudo bash -c "cat <<EOF > /usr/share/nginx/html/error-404.html
Ceci n'est pas une page
EOF"

sudo service nginx restart
