#!/usr/bin/env bash
# instlal HAProxy on Load Balancer server
sudo apt -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

echo "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 182977-web-01 54.146.93.177:80 check
    server 182977-web-02 35.174.205.164:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
