#!/usr/bin/env bash
# instlal HAProxy on Load Balancer server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

echo "
frontend myfrontend
    bind 127.0.0.1:80
    default_backend myservers

backend myservers
    server 182977-web-01 54.146.93.177:80
    server 182977-web-02 35.174.205.164:80
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
