#!/usr/bin/env bash
# Process and pid file
my_pid="/var/run/myscript.pid"
echo $$ | sudo tee "$my_pid" > /dev/null
trap 'echo "I hate the kill command"; sudo rm -f "$my_pid"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'sudo rm -f "$my_pid"; exit' SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
