#!/usr/bin/env bash
# Manage my process
proc="manage_my_process"
pid_proc="/var/run/my_process.pid"
start()
{
	./"$proc" &
	echo "$!" | sudo tee $pid_proc > /dev/null
	echo "manage_my_process started"
}
stop()
{
	pid=$(sudo cat "$pid_proc")
	sudo rm -f $pid_proc
	kill "$pid"
	echo "manage_my_process stopped"
}
restart()
{
	pid=$(sudo cat "$pid_proc")
	sudo rm -f "$pid_proc"
	kill "$pid"
	./"$proc" &
	echo "$!" | sudo tee $pid_proc > /dev/null
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit
		;;
esac
