#!/usr/bin/env bash
# More exercises on looping with while
i=0
while [[ $i -lt 10 ]]
do
	i=$((i + 1))
	if [[ $i -eq 4 ]]; then
		echo "bad luck"
		continue
	elif [[ $i -eq 8 ]]; then
		echo "good luck"
		continue
	fi
	echo "Best School"
done
