#!/usr/bin/env bash
# Configure Localhost and Facebook.com
host="/etc/hosts"
temp="hosts.new"
cp "$host" "$temp"
sed -E -i 's/^([0-9]{1,3}\.){3}[0-9]{1,3}\s+localhost$/127.0.0.2    localhost/' "$temp"
sed -i '1s/^/8.8.8.8    facebook.com\n/' "$temp"
sudo cp -f "$temp" "$host"
rm "$temp"
